import { useMediaQuery } from "@chakra-ui/react"
import Head from 'next/head'
import { HomeMobile } from './components/style/HomeMobile'
import { HomeWeb } from './components/style/HomeWeb'

export default function Home() {
  const [isMobile] = useMediaQuery("(max-width: 768px)")

  return (
    <>
      <Head>
        <title>PROF - starmax</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isMobile ? <HomeMobile /> : <HomeWeb />}
    </>
  )
}

